version: "2"

linters:
  default: all
  disable:
    - depguard
  settings:
    errcheck:
      exclude-functions:
        - (go.bug.st/serial.Port).Close

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
