version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - dupl
    - misspell
    - depguard
    - gosec
  settings:
    errcheck:
      exclude-functions:
        - (go.bug.st/serial.Port).Close

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
