version: "2"

linters:    
  settings:
    errcheck:
      exclude-functions:
        - serial.Port
        - Close
      verbose: true

# formatters:
#   enable:
#     - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
