# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          go mod download

      # 4. Linter et analyse de qualité
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.53.3
          args: run ./cmd/...

      # 5. Build
      - name: Build
        run: go build -v ./...

      # 6. Test unitaires avec couverture
      - name: Run tests
        run: |
          go test -v -coverprofile=coverage.out ./cmd/...
      
      # 7. Afficher le rapport de couverture
      - name: Show coverage
        run: |
          go tool cover -func=coverage.out

      # 8. Optionnel: publier la couverture sur Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          fail_ci_if_error: true